In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/new_insurance_data (1).csv")

In [3]:
#eda commands
#head-displays initial rows
df.head()

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
0,18.0,male,23.21,0.0,no,29087.54313,17.0,715428.0,4720920.992,0.0,55784970.05,southeast,1121.8739
1,18.0,male,30.14,0.0,no,39053.67437,7.0,699157.0,4329831.676,0.0,13700885.19,southeast,1131.5066
2,18.0,male,33.33,0.0,no,39023.62759,19.0,702341.0,6884860.774,0.0,73523107.27,southeast,1135.9407
3,18.0,male,33.66,0.0,no,28185.39332,11.0,700250.0,4274773.550,0.0,75819679.60,southeast,1136.3994
4,18.0,male,34.10,0.0,no,14697.85941,16.0,711584.0,3787293.921,0.0,23012320.01,southeast,1137.0110

In [4]:
df.tail(5)

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
1333,33.0,female,35.530,0.0,yes,63142.25346,32.0,1091267.0,170380500.5,2.0,3.101107e+09,northwest,55135.40209
1334,31.0,female,38.095,1.0,yes,43419.95227,31.0,1107872.0,201515184.8,2.0,3.484216e+09,northeast,58571.07448
1335,52.0,male,34.485,3.0,yes,52458.92353,25.0,1092005.0,223644981.3,2.0,3.640807e+09,northwest,60021.39897
1336,45.0,male,30.360,0.0,yes,69927.51664,34.0,1106821.0,252892382.6,3.0,4.006359e+09,southeast,62592.87309
1337,54.0,female,47.410,0.0,yes,63982.80926,31.0,1100328.0,261631699.3,3.0,4.117197e+09,southeast,63770.42801

In [5]:
#retrieves the info of the columns with non-null values & datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   age                              1329 non-null   float64
 1   sex                              1338 non-null   object
 2   bmi                              1335 non-null   float64
 3   children                         1333 non-null   float64
 4   smoker                           1338 non-null   object
 5   Claim_Amount                     1324 non-null   float64
 6   past_consultations               1332 non-null   float64
 7   num_of_steps                     1335 non-null   float64
 8   Hospital_expenditure             1334 non-null   float64
 9   NUmber_of_past_hospitalizations  1336 non-null   float64
 10  Anual_Salary                     1332 non-null   float64
 11  region                           1338 non-null   object
 12  charges                          1338 non-null   float64
dtypes: float64(10), object(3)
memory usage: 136.0+ KB

In [6]:
#describes the stastical summary of the columns like count,mean,std,min,25%,50%,75%,max
df.describe()

,age,bmi,children,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,charges
count,1329.000000,1335.000000,1333.000000,1324.000000,1332.000000,1.335000e+03,1.334000e+03,1336.000000,1.332000e+03,1338.000000
mean,39.310008,30.665112,1.090773,33361.327180,15.216216,9.100047e+05,1.584179e+07,1.060629,3.696849e+08,13270.422265
std,14.034818,6.101690,1.201856,15617.288337,7.467723,9.188612e+04,2.669305e+07,0.533583,5.668843e+08,12110.011237
min,18.000000,15.960000,0.000000,1920.136268,1.000000,6.954300e+05,2.945253e+04,0.000000,2.747072e+06,1121.873900
25%,27.000000,26.302500,0.000000,20768.860390,9.000000,8.471995e+05,4.077633e+06,1.000000,7.701932e+07,4740.287150
50%,39.000000,30.400000,1.000000,33700.310675,15.000000,9.143000e+05,7.490337e+06,1.000000,1.419361e+08,9382.033000
75%,51.000000,34.687500,2.000000,45052.331957,20.000000,9.716840e+05,1.084082e+07,1.000000,3.243499e+08,16639.912515
max,64.000000,53.130000,5.000000,77277.988480,40.000000,1.107872e+06,2.616317e+08,3.000000,4.117197e+09,63770.428010

In [7]:
#columns-give the names of all columns in the data
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'Claim_Amount',
       'past_consultations', 'num_of_steps', 'Hospital_expenditure',
       'NUmber_of_past_hospitalizations', 'Anual_Salary', 'region', 'charges'],
      dtype='object')

In [8]:
#to find and handle the missing values
df.isnull().sum()
#it returns the no.of missing NaN values in each column of the dataframe

age                                 9
sex                                 0
bmi                                 3
children                            5
smoker                              0
Claim_Amount                       14
past_consultations                  6
num_of_steps                        3
Hospital_expenditure                4
NUmber_of_past_hospitalizations     2
Anual_Salary                        6
region                              0
charges                             0
dtype: int64

In [9]:
#shows missing values and returns True or False
df.isnull()

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,False,False,False,False,False,False,False,False,False,False,False,False,False
1334,False,False,False,False,False,False,False,False,False,False,False,False,False
1335,False,False,False,False,False,False,False,False,False,False,False,False,False
1336,False,False,False,False,False,False,False,False,False,False,False,False,False
1337,False,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
#to know missing values row wise are
df.isnull().sum(axis=1)

0       0
1       0
2       0
3       0
4       0
       ..
1333    0
1334    0
1335    0
1336    0
1337    0
Length: 1338, dtype: int64

In [11]:
#shows True for non-missing values
df.notnull()

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
0,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,True,True,True,True,True,True,True,True,True,True,True,True,True
1334,True,True,True,True,True,True,True,True,True,True,True,True,True
1335,True,True,True,True,True,True,True,True,True,True,True,True,True
1336,True,True,True,True,True,True,True,True,True,True,True,True,True
1337,True,True,True,True,True,True,True,True,True,True,True,True,True

In [12]:
#shows non-missing values for each column
df.notnull().sum()

age                                1329
sex                                1338
bmi                                1335
children                           1333
smoker                             1338
Claim_Amount                       1324
past_consultations                 1332
num_of_steps                       1335
Hospital_expenditure               1334
NUmber_of_past_hospitalizations    1336
Anual_Salary                       1332
region                             1338
charges                            1338
dtype: int64

In [13]:
#shows missing values and returns True for NaN values and False for Other values
df.isna()

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,False,False,False,False,False,False,False,False,False,False,False,False,False
1334,False,False,False,False,False,False,False,False,False,False,False,False,False
1335,False,False,False,False,False,False,False,False,False,False,False,False,False
1336,False,False,False,False,False,False,False,False,False,False,False,False,False
1337,False,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
#same as df.isnull().sum()
df.isna().sum()

age                                 9
sex                                 0
bmi                                 3
children                            5
smoker                              0
Claim_Amount                       14
past_consultations                  6
num_of_steps                        3
Hospital_expenditure                4
NUmber_of_past_hospitalizations     2
Anual_Salary                        6
region                              0
charges                             0
dtype: int64

In [15]:
#True means here the row is duplicated
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool

In [16]:
#To display only duplicated rows
df[df.duplicated()]

Empty DataFrame
Columns: [age, sex, bmi, children, smoker, Claim_Amount, past_consultations, num_of_steps, Hospital_expenditure, NUmber_of_past_hospitalizations, Anual_Salary, region, charges]
Index: []

In [17]:
#count no.of duplicated rows
df.duplicated().sum()

np.int64(0)

In [18]:
#to remove duplicates
df.drop_duplicates()

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
0,18.0,male,23.210,0.0,no,29087.54313,17.0,715428.0,4.720921e+06,0.0,5.578497e+07,southeast,1121.87390
1,18.0,male,30.140,0.0,no,39053.67437,7.0,699157.0,4.329832e+06,0.0,1.370089e+07,southeast,1131.50660
2,18.0,male,33.330,0.0,no,39023.62759,19.0,702341.0,6.884861e+06,0.0,7.352311e+07,southeast,1135.94070
3,18.0,male,33.660,0.0,no,28185.39332,11.0,700250.0,4.274774e+06,0.0,7.581968e+07,southeast,1136.39940
4,18.0,male,34.100,0.0,no,14697.85941,16.0,711584.0,3.787294e+06,0.0,2.301232e+07,southeast,1137.01100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,33.0,female,35.530,0.0,yes,63142.25346,32.0,1091267.0,1.703805e+08,2.0,3.101107e+09,northwest,55135.40209
1334,31.0,female,38.095,1.0,yes,43419.95227,31.0,1107872.0,2.015152e+08,2.0,3.484216e+09,northeast,58571.07448
1335,52.0,male,34.485,3.0,yes,52458.92353,25.0,1092005.0,2.236450e+08,2.0,3.640807e+09,northwest,60021.39897
1336,45.0,male,30.360,0.0,yes,69927.51664,34.0,1106821.0,2.528924e+08,3.0,4.006359e+09,southeast,62592.87309
1337,54.0,female,47.410,0.0,yes,63982.80926,31.0,1100328.0,2.616317e+08,3.0,4.117197e+09,southeast,63770.42801

In [19]:
#remove duplicates and save changes
df.drop_duplicates(inplace=True)

In [20]:
#check duplicates on a specific column
df.duplicated(subset=["bmi"])

0       False
1       False
2       False
3       False
4       False
        ...
1333     True
1334     True
1335     True
1336    False
1337    False
Length: 1338, dtype: bool

In [21]:
#count duplicate values in a column
df["bmi"].duplicated().sum()

np.int64(790)

In [22]:
#find all duplicates
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [age, sex, bmi, children, smoker, Claim_Amount, past_consultations, num_of_steps, Hospital_expenditure, NUmber_of_past_hospitalizations, Anual_Salary, region, charges]
Index: []

In [23]:
#to find unique values
df["age"].unique()

array([18., 19., nan, 20., 21., 22., 23., 24., 25., 26., 27., 28., 29.,
       31., 30., 33., 32., 34., 36., 37., 35., 38., 40., 39., 41., 42.,
       43., 44., 46., 45., 48., 47., 49., 50., 51., 52., 53., 54., 55.,
       56., 57., 58., 59., 60., 61., 62., 63., 64.])

In [24]:
#count frequency of each value
df["bmi"].value_counts()

bmi
32.300    13
28.310     9
30.800     8
31.350     8
30.875     8
          ..
44.880     1
42.750     1
36.400     1
30.360     1
47.410     1
Name: count, Length: 547, dtype: int64

In [25]:
#gives the stastical summary data of each column
df.describe(include='all')

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
count,1329.000000,1338,1335.000000,1333.000000,1338,1324.000000,1332.000000,1.335000e+03,1.334000e+03,1336.000000,1.332000e+03,1338,1338.000000
unique,NaN,2,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN
top,NaN,male,NaN,NaN,no,NaN,NaN,NaN,NaN,NaN,NaN,southeast,NaN
freq,NaN,676,NaN,NaN,1064,NaN,NaN,NaN,NaN,NaN,NaN,364,NaN
mean,39.310008,NaN,30.665112,1.090773,NaN,33361.327180,15.216216,9.100047e+05,1.584179e+07,1.060629,3.696849e+08,NaN,13270.422265
std,14.034818,NaN,6.101690,1.201856,NaN,15617.288337,7.467723,9.188612e+04,2.669305e+07,0.533583,5.668843e+08,NaN,12110.011237
min,18.000000,NaN,15.960000,0.000000,NaN,1920.136268,1.000000,6.954300e+05,2.945253e+04,0.000000,2.747072e+06,NaN,1121.873900
25%,27.000000,NaN,26.302500,0.000000,NaN,20768.860390,9.000000,8.471995e+05,4.077633e+06,1.000000,7.701932e+07,NaN,4740.287150
50%,39.000000,NaN,30.400000,1.000000,NaN,33700.310675,15.000000,9.143000e+05,7.490337e+06,1.000000,1.419361e+08,NaN,9382.033000
75%,51.000000,NaN,34.687500,2.000000,NaN,45052.331957,20.000000,9.716840e+05,1.084082e+07,1.000000,3.243499e+08,NaN,16639.912515
max,64.000000,NaN,53.130000,5.000000,NaN,77277.988480,40.000000,1.107872e+06,2.616317e+08,3.000000,4.117197e+09,NaN,63770.428010

In [26]:
#mean calculates the average of numerical multiple values
df["bmi"].mean()

np.float64(30.665112359550562)

In [27]:
#here it can calculates the multiple columns at the same time
df[["bmi","children"]].mean()

bmi         30.665112
children     1.090773
dtype: float64

In [28]:
df.mean(numeric_only=True)

age                                3.931001e+01
bmi                                3.066511e+01
children                           1.090773e+00
Claim_Amount                       3.336133e+04
past_consultations                 1.521622e+01
num_of_steps                       9.100047e+05
Hospital_expenditure               1.584179e+07
NUmber_of_past_hospitalizations    1.060629e+00
Anual_Salary                       3.696849e+08
charges                            1.327042e+04
dtype: float64

In [29]:
df["bmi"].median()

30.4

In [30]:
df.median(numeric_only=True)

age                                3.900000e+01
bmi                                3.040000e+01
children                           1.000000e+00
Claim_Amount                       3.370031e+04
past_consultations                 1.500000e+01
num_of_steps                       9.143000e+05
Hospital_expenditure               7.490337e+06
NUmber_of_past_hospitalizations    1.000000e+00
Anual_Salary                       1.419361e+08
charges                            9.382033e+03
dtype: float64

In [31]:
df.mode()

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
0,18.0,male,32.3,0.0,no,1920.136268,20.0,695430.0,2.945253e+04,1.0,2.747072e+06,southeast,1639.5631
1,NaN,NaN,NaN,NaN,NaN,2912.590584,NaN,699157.0,3.582244e+04,NaN,3.150786e+06,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,3037.725919,NaN,699159.0,5.764709e+04,NaN,3.550884e+06,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,3370.398323,NaN,700250.0,7.795603e+04,NaN,4.038872e+06,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,3768.603033,NaN,701227.0,8.748337e+04,NaN,4.979936e+06,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1092005.0,2.015152e+08,NaN,4.006359e+09,NaN,NaN
1331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1095960.0,2.236450e+08,NaN,4.117197e+09,NaN,NaN
1332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1100328.0,2.528924e+08,NaN,NaN,NaN,NaN
1333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1106821.0,2.616317e+08,NaN,NaN,NaN,NaN
1334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1107872.0,NaN,NaN,NaN,NaN,NaN

In [32]:
df.min()

age                                       18.0
sex                                     female
bmi                                      15.96
children                                   0.0
smoker                                      no
Claim_Amount                       1920.136268
past_consultations                         1.0
num_of_steps                          695430.0
Hospital_expenditure               29452.53296
NUmber_of_past_hospitalizations            0.0
Anual_Salary                       2747071.908
region                               northeast
charges                              1121.8739
dtype: object

In [33]:
df.max()

age                                        64.0
sex                                        male
bmi                                       53.13
children                                    5.0
smoker                                      yes
Claim_Amount                        77277.98848
past_consultations                         40.0
num_of_steps                          1107872.0
Hospital_expenditure                261631699.3
NUmber_of_past_hospitalizations             3.0
Anual_Salary                       4117196637.0
region                                southwest
charges                             63770.42801
dtype: object

In [34]:
df["bmi"].min()

15.96

In [35]:
df["smoker"].max()

'yes'

In [36]:
df["bmi"].max()

53.13

In [37]:
df["age"].max()

64.0

In [38]:
df["age"].min()

18.0

In [39]:
#std measures how far from the data values from the mean
df["age"].std()

14.03481785145205

In [40]:
df.std(numeric_only=True)

age                                1.403482e+01
bmi                                6.101690e+00
children                           1.201856e+00
Claim_Amount                       1.561729e+04
past_consultations                 7.467723e+00
num_of_steps                       9.188612e+04
Hospital_expenditure               2.669305e+07
NUmber_of_past_hospitalizations    5.335831e-01
Anual_Salary                       5.668843e+08
charges                            1.211001e+04
dtype: float64

In [41]:
df[['age','bmi']]

       age     bmi
0     18.0  23.210
1     18.0  30.140
2     18.0  33.330
3     18.0  33.660
4     18.0  34.100
...    ...     ...
1333  33.0  35.530
1334  31.0  38.095
1335  52.0  34.485
1336  45.0  30.360
1337  54.0  47.410

[1338 rows x 2 columns]

In [42]:
#variance is the square of the standard deviation
df['age'].var()

196.97611212343713

In [43]:
df.var(numeric_only=True)

age                                1.969761e+02
bmi                                3.723062e+01
children                           1.444457e+00
Claim_Amount                       2.438997e+08
past_consultations                 5.576689e+01
num_of_steps                       8.443059e+09
Hospital_expenditure               7.125188e+14
NUmber_of_past_hospitalizations    2.847109e-01
Anual_Salary                       3.213578e+17
charges                            1.466524e+08
dtype: float64

In [44]:
df

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
0,18.0,male,23.210,0.0,no,29087.54313,17.0,715428.0,4.720921e+06,0.0,5.578497e+07,southeast,1121.87390
1,18.0,male,30.140,0.0,no,39053.67437,7.0,699157.0,4.329832e+06,0.0,1.370089e+07,southeast,1131.50660
2,18.0,male,33.330,0.0,no,39023.62759,19.0,702341.0,6.884861e+06,0.0,7.352311e+07,southeast,1135.94070
3,18.0,male,33.660,0.0,no,28185.39332,11.0,700250.0,4.274774e+06,0.0,7.581968e+07,southeast,1136.39940
4,18.0,male,34.100,0.0,no,14697.85941,16.0,711584.0,3.787294e+06,0.0,2.301232e+07,southeast,1137.01100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,33.0,female,35.530,0.0,yes,63142.25346,32.0,1091267.0,1.703805e+08,2.0,3.101107e+09,northwest,55135.40209
1334,31.0,female,38.095,1.0,yes,43419.95227,31.0,1107872.0,2.015152e+08,2.0,3.484216e+09,northeast,58571.07448
1335,52.0,male,34.485,3.0,yes,52458.92353,25.0,1092005.0,2.236450e+08,2.0,3.640807e+09,northwest,60021.39897
1336,45.0,male,30.360,0.0,yes,69927.51664,34.0,1106821.0,2.528924e+08,3.0,4.006359e+09,southeast,62592.87309
1337,54.0,female,47.410,0.0,yes,63982.80926,31.0,1100328.0,2.616317e+08,3.0,4.117197e+09,southeast,63770.42801

In [78]:
df[(df["age"]>20)|(df["bmi"]>25.0)]

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
1,18.0,male,30.140,0.0,no,39053.67437,7.0,699157.0,4.329832e+06,0.0,1.370089e+07,southeast,1131.50660
2,18.0,male,33.330,0.0,no,39023.62759,19.0,702341.0,6.884861e+06,0.0,7.352311e+07,southeast,1135.94070
3,18.0,male,33.660,0.0,no,28185.39332,11.0,700250.0,4.274774e+06,0.0,7.581968e+07,southeast,1136.39940
4,18.0,male,34.100,0.0,no,14697.85941,16.0,711584.0,3.787294e+06,0.0,2.301232e+07,southeast,1137.01100
5,18.0,male,34.430,0.0,no,26488.33912,20.0,717162.0,3.696161e+06,0.0,NaN,southeast,1137.46970
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,33.0,female,35.530,0.0,yes,63142.25346,32.0,1091267.0,1.703805e+08,2.0,3.101107e+09,northwest,55135.40209
1334,31.0,female,38.095,1.0,yes,43419.95227,31.0,1107872.0,2.015152e+08,2.0,3.484216e+09,northeast,58571.07448
1335,52.0,male,34.485,3.0,yes,52458.92353,25.0,1092005.0,2.236450e+08,2.0,3.640807e+09,northwest,60021.39897
1336,45.0,male,30.360,0.0,yes,69927.51664,34.0,1106821.0,2.528924e+08,3.0,4.006359e+09,southeast,62592.87309
1337,54.0,female,47.410,0.0,yes,63982.80926,31.0,1100328.0,2.616317e+08,3.0,4.117197e+09,southeast,63770.42801

In [45]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [46]:
df.size

17394

In [47]:
df.ndim

2

In [48]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'Claim_Amount',
       'past_consultations', 'num_of_steps', 'Hospital_expenditure',
       'NUmber_of_past_hospitalizations', 'Anual_Salary', 'region', 'charges'],
      dtype='object')

In [49]:
df.shape

(1338, 13)

In [50]:
#to create a dataframe in pandas
import pandas as pd
data={"Name":['Alice','Bob','Charlie'],
      "Marks":[98,90,95],
      "Age":[21,20,19]}
df1=pd.DataFrame(data)
print(df1)

      Name  Marks  Age
0    Alice     98   21
1      Bob     90   20
2  Charlie     95   19

In [51]:
#Creating Series from a list
import pandas as pd
s=pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [52]:
#Creating a series with a custom index
import pandas as pd
s1=pd.Series([90,78,56],index=["Alice","Bob","Charlie"])
print(s1)
print(s1["Charlie"])

Alice      90
Bob        78
Charlie    56
dtype: int64
56

In [53]:
#creating a series from a dictionary
import pandas as pd
data={"Maths":90,
      "Science":98,
      "English":99
      }
s2=pd.Series(data)
print(s2)

Maths      90
Science    98
English    99
dtype: int64

In [54]:
#create a series with same value
import pandas as pd
s3=pd.Series(5,index=["K","o","L","L","U","R","I"])
print(s3)

K    5
o    5
L    5
L    5
U    5
R    5
I    5
dtype: int64

In [55]:
#create a series form dataframe column
import pandas as pd
df2=pd.DataFrame({"Name":["Mom","Dad","Harsh"],
                  "Age":[57,53,22],
                  "Gender":["F","M","F"]
                  })
age_series=df2["Age"]
print(df2)
print(age_series)

    Name  Age Gender
0    Mom   57      F
1    Dad   53      M
2  Harsh   22      F
0    57
1    53
2    22
Name: Age, dtype: int64

Filtering

In [57]:
#select the rows or data on the basis of specific conditions
import pandas as pd
student=pd.DataFrame({
    "Name":["X","Y","Z"],
    "Age":[12,78,90],
    "Sex":["M","F","T"],
    "Marks":[90,78,89],
    "City":["Mumbai","Andhra Pradesh","Chennai"]
    })
student

  Name  Age Sex  Marks            City
0    X   12   M     90          Mumbai
1    Y   78   F     78  Andhra Pradesh
2    Z   90   T     89         Chennai

In [61]:
student[student['Sex']=="T"]

  Name  Age Sex  Marks     City
2    Z   90   T     89  Chennai

In [64]:
student["Marks"]>=90

0     True
1    False
2    False
Name: Marks, dtype: bool

In [65]:
student[student["City"]=="Mumbai"]

  Name  Age Sex  Marks    City
0    X   12   M     90  Mumbai

In [66]:
student[student["Age"]<20]

  Name  Age Sex  Marks    City
0    X   12   M     90  Mumbai

In [67]:
print(True and True)

True

In [68]:
print(True and False)

False

In [72]:
print(False and False)

False

In [69]:
print(True or False)

True

In [70]:
print(True or True)

True

In [71]:
print(False or False)

False

In [76]:
student[(student["Age"]>20) & (student["Sex"]=="T")]

  Name  Age Sex  Marks     City
2    Z   90   T     89  Chennai

In [77]:
student[(student["Marks"]>80)|(student["City"]=="Andhra Pradesh")]

  Name  Age Sex  Marks            City
0    X   12   M     90          Mumbai
1    Y   78   F     78  Andhra Pradesh
2    Z   90   T     89         Chennai

In [79]:
student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Sex     3 non-null      object
 3   Marks   3 non-null      int64
 4   City    3 non-null      object
dtypes: int64(2), object(3)
memory usage: 252.0+ bytes

In [80]:
student[~(student["Sex"]=="T")]

  Name  Age Sex  Marks            City
0    X   12   M     90          Mumbai
1    Y   78   F     78  Andhra Pradesh

In [82]:
student[(student["City"]=="Mumbai")& (student["Age"]<20)]

  Name  Age Sex  Marks    City
0    X   12   M     90  Mumbai

In [83]:
student[~(student["City"]=="Chennai")]

  Name  Age Sex  Marks            City
0    X   12   M     90          Mumbai
1    Y   78   F     78  Andhra Pradesh

In [86]:
student[(student["Name"]=="Z")|(student["Age"]>50)]

  Name  Age Sex  Marks            City
1    Y   78   F     78  Andhra Pradesh
2    Z   90   T     89         Chennai

In [87]:
df[(df["region"]=="southwest") & (df["smoker"]=="yes")]

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
939,19.0,female,21.7,0.0,yes,51149.48177,13.0,954114.0,5.207775e+06,1.0,2.314991e+08,southwest,13844.50600
990,38.0,male,19.3,0.0,yes,47093.96209,8.0,962832.0,5.609627e+06,1.0,3.180444e+08,southwest,15820.69900
996,20.0,male,27.3,0.0,yes,32076.78940,21.0,979726.0,1.012317e+07,1.0,3.500268e+08,southwest,16232.84700
997,19.0,male,27.7,0.0,yes,21877.72685,10.0,959504.0,6.042504e+06,1.0,3.384877e+08,southwest,16297.84600
1006,19.0,female,27.9,0.0,yes,54770.51636,10.0,983504.0,9.310019e+06,1.0,3.223425e+08,southwest,16884.92400
1008,19.0,female,28.3,0.0,yes,54312.36135,15.0,979696.0,1.482590e+07,1.0,3.784483e+08,southwest,17081.08000
1016,32.0,female,24.6,0.0,yes,44462.69482,21.0,993140.0,1.437146e+07,1.0,3.428884e+08,southwest,17496.30600
1024,21.0,male,25.7,4.0,yes,23327.30277,14.0,974525.0,8.800807e+06,1.0,3.333838e+08,southwest,17942.10600
1030,30.0,male,24.4,3.0,yes,23306.74970,20.0,980302.0,1.560269e+07,1.0,3.796690e+08,southwest,18259.21600
1033,36.0,female,22.6,2.0,yes,55448.94112,10.0,978870.0,8.446015e+06,1.0,3.916593e+08,southwest,18608.26200
1044,39.0,female,18.3,5.0,yes,16552.37406,27.0,985707.0,9.788350e+06,1.0,4.069698e+08,southwest,19023.26000
1045,33.0,male,27.1,1.0,yes,39952.92288,27.0,996320.0,1.419652e+07,1.0,4.537275e+08,southwest,19040.87600
1048,31.0,male,25.9,3.0,yes,46619.40230,27.0,989387.0,1.361938e+07,1.0,3.812895e+08,southwest,19199.94400
1063,25.0,male,29.7,3.0,yes,31490.98299,19.0,985576.0,1.735298e+07,1.0,4.622047e+08,southwest,19933.45800
1067,20.0,female,21.8,0.0,yes,59930.32342,19.0,1000729.0,1.747125e+07,1.0,4.889329e+08,southwest,20167.33603
1081,39.0,male,28.3,1.0,yes,35683.13567,9.0,994758.0,1.036247e+07,1.0,4.770941e+08,southwest,21082.16000
1099,42.0,male,30.0,0.0,yes,21287.87513,18.0,998023.0,1.548734e+07,1.0,5.820684e+08,southwest,22144.03200
1106,43.0,female,26.7,2.0,yes,18777.25866,28.0,1006237.0,1.472207e+07,1.0,5.715081e+08,southwest,22478.60000
1114,49.0,male,25.6,2.0,yes,43564.76221,20.0,993898.0,1.575212e+07,2.0,6.222796e+08,southwest,23306.54700
1117,48.0,male,28.0,1.0,yes,26836.14115,18.0,999525.0,2.205387e+07,2.0,6.393785e+08,southwest,23568.27200
1128,50.0,female,27.6,1.0,yes,23928.00250,13.0,1014236.0,2.450067e+07,2.0,6.405124e+08,southwest,24520.26400
1138,47.0,male,29.8,3.0,yes,48524.08380,13.0,1024019.0,2.419276e+07,2.0,7.222589e+08,southwest,25309.48900
1140,54.0,male,25.1,3.0,yes,45956.96538,19.0,1027713.0,1.709004e+07,2.0,6.461079e+08,southwest,25382.29700
1192,25.0,female,30.2,0.0,yes,38838.01180,19.0,1049108.0,4.202504e+07,2.0,1.159497e+09,southwest,33900.65300
1194,23.0,female,31.4,0.0,yes,51777.80176,14.0,1034239.0,4.106056e+07,2.0,1.250399e+09,southwest,34166.27300
1198,24.0,male,32.7,0.0,yes,32162.63541,31.0,1033108.0,4.818232e+07,2.0,1.281238e+09,southwest,34472.84100
1201,19.0,male,34.8,0.0,yes,28937.12615,20.0,1043930.0,5.133828e+07,2.0,1.284642e+09,southwest,34779.61500
1203,19.0,male,34.9,0.0,yes,24737.14715,20.0,1048323.0,4.936102e+07,2.0,1.238833e+09,southwest,34828.65400
1204,27.0,female,31.4,0.0,yes,47234.85641,21.0,1049193.0,5.118418e+07,2.0,1.291220e+09,southwest,34838.87300
1208,34.0,male,30.8,0.0,yes,56919.89226,30.0,1058101.0,4.519362e+07,2.0,1.313324e+09,southwest,35491.64000
1209,22.0,male,35.6,0.0,yes,35705.20025,30.0,1044306.0,5.034885e+07,2.0,1.361973e+09,southwest,35585.57600
1212,26.0,male,32.9,2.0,yes,60530.65195,33.0,1051788.0,4.771594e+07,2.0,1.350333e+09,southwest,36085.21900
1216,29.0,male,34.4,0.0,yes,24969.29952,25.0,1052642.0,4.883718e+07,2.0,1.377813e+09,southwest,36197.69900
1219,19.0,female,34.7,2.0,yes,40463.31572,32.0,1046202.0,5.443057e+07,2.0,1.417229e+09,southwest,36397.57600
1221,30.0,male,35.3,0.0,yes,40267.69557,26.0,1037793.0,5.465370e+07,2.0,1.454837e+09,southwest,36837.46700
1225,33.0,female,33.5,0.0,yes,71776.98023,19.0,1046608.0,5.214773e+07,2.0,1.382499e+09,southwest,37079.37200
1234,43.0,male,27.8,0.0,yes,69768.26145,18.0,1052639.0,6.081301e+07,2.0,1.526205e+09,southwest,37829.72420
1238,20.0,male,39.4,2.0,yes,33677.11676,21.0,1040225.0,5.892443e+07,2.0,1.483202e+09,southwest,38344.56600
1239,36.0,male,33.4,2.0,yes,48649.84857,32.0,1048134.0,5.881031e+07,2.0,1.573067e+09,southwest,38415.47400
1242,31.0,male,36.3,2.0,yes,31453.59567,30.0,1072229.0,6.691343e+07,2.0,1.509148e+09,southwest,38711.00000
1245,44.0,male,30.2,2.0,yes,31398.38359,17.0,1072997.0,6.560843e+07,2.0,1.530159e+09,southwest,38998.54600
1248,30.0,male,37.8,2.0,yes,62314.70215,17.0,1062645.0,6.734633e+07,2.0,1.625994e+09,southwest,39241.44200
1254,49.0,male,30.9,0.0,yes,62866.17718,17.0,1045310.0,6.679782e+07,2.0,1.589087e+09,southwest,39727.61400
1256,37.0,female,34.8,2.0,yes,59342.31590,18.0,1065885.0,7.086640e+07,2.0,1.625086e+09,southwest,39836.51900
1260,39.0,male,35.3,2.0,yes,65802.95090,20.0,1075963.0,6.481584e+07,2.0,1.669792e+09,southwest,40103.89000
1261,37.0,male,34.1,4.0,yes,52206.09340,30.0,1068775.0,6.842734e+07,2.0,1.648384e+09,southwest,40182.24600
1271,46.0,female,34.6,1.0,yes,31098.42642,30.0,1058983.0,7.752573e+07,2.0,1.814766e+09,southwest,41661.60200
1283,50.0,male,34.2,2.0,yes,66956.07816,21.0,1057149.0,7.935004e+07,2.0,1.915603e+09,southwest,42856.83800
1298,29.0,male,35.5,2.0,yes,29567.96081,28.0,1080849.0,9.217915e+07,2.0,2.064737e+09,southwest,44585.45587
1304,37.0,female,47.6,2.0,yes,37088.16328,30.0,1061520.0,1.003198e+08,2.0,2.202513e+09,southwest,46113.51100
1315,64.0,female,31.3,2.0,yes,53826.84148,21.0,1067625.0,1.099289e+08,2.0,2.317318e+09,southwest,47291.05500
1316,63.0,female,32.2,2.0,yes,53731.77001,35.0,1059107.0,1.099758e+08,2.0,2.246148e+09,southwest,47305.30500
1317,61.0,male,36.3,1.0,yes,42647.18135,26.0,1066986.0,1.145664e+08,2.0,2.336563e+09,southwest,47403.88000
1321,64.0,female,33.8,1.0,yes,54925.38808,38.0,1064345.0,1.185198e+08,2.0,2.380291e+09,southwest,47928.03000
1322,60.0,male,39.9,0.0,yes,40836.22323,33.0,1084625.0,1.156776e+08,2.0,2.409971e+09,southwest,48173.36100
1327,63.0,female,37.7,0.0,yes,45403.93473,35.0,1085496.0,1.221800e+08,2.0,2.446348e+09,southwest,48824.45000
1331,28.0,male,36.4,1.0,yes,55590.75527,26.0,1080113.0,1.440616e+08,2.0,2.682705e+09,southwest,51194.55914
1332,60.0,male,32.8,0.0,yes,77277.98848,40.0,1095960.0,1.480346e+08,2.0,2.780642e+09,southwest,52590.82939

In [88]:
df[df["region"]=="southwest"]

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
10,19.0,male,19.8,0.0,no,16980.214030,2.0,706796.0,4.981703e+06,0.0,7.007611e+07,southwest,1241.56500
11,19.0,male,20.3,0.0,no,1920.136268,NaN,695430.0,3.786542e+06,0.0,2.747072e+06,southwest,1242.26000
12,19.0,male,20.7,0.0,no,3927.892067,4.0,723928.0,5.013945e+06,NaN,9.462889e+07,southwest,1242.81600
13,19.0,male,27.6,0.0,no,46780.546480,8.0,701227.0,NaN,0.0,3.842163e+07,southwest,1252.40700
14,19.0,male,28.7,0.0,no,36778.503830,3.0,724149.0,8.213685e+06,0.0,1.790462e+07,southwest,1253.93600
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1321,64.0,female,33.8,1.0,yes,54925.388080,38.0,1064345.0,1.185198e+08,2.0,2.380291e+09,southwest,47928.03000
1322,60.0,male,39.9,0.0,yes,40836.223230,33.0,1084625.0,1.156776e+08,2.0,2.409971e+09,southwest,48173.36100
1327,63.0,female,37.7,0.0,yes,45403.934730,35.0,1085496.0,1.221800e+08,2.0,2.446348e+09,southwest,48824.45000
1331,28.0,male,36.4,1.0,yes,55590.755270,26.0,1080113.0,1.440616e+08,2.0,2.682705e+09,southwest,51194.55914
1332,60.0,male,32.8,0.0,yes,77277.988480,40.0,1095960.0,1.480346e+08,2.0,2.780642e+09,southwest,52590.82939

In [89]:
df[df['region']=="southwest"]["age"]

10      19.0
11      19.0
12      19.0
13      19.0
14      19.0
        ...
1321    64.0
1322    60.0
1327    63.0
1331    28.0
1332    60.0
Name: age, Length: 325, dtype: float64

In [90]:
df[df["region"]=="southwest"]['Anual_Salary']

10      7.007611e+07
11      2.747072e+06
12      9.462889e+07
13      3.842163e+07
14      1.790462e+07
            ...
1321    2.380291e+09
1322    2.409971e+09
1327    2.446348e+09
1331    2.682705e+09
1332    2.780642e+09
Name: Anual_Salary, Length: 325, dtype: float64

In [91]:
df[(df['region']=="southwest")|(df['region']=="northwest")]['Anual_Salary']

10      7.007611e+07
11      2.747072e+06
12      9.462889e+07
13      3.842163e+07
14      1.790462e+07
            ...
1327    2.446348e+09
1331    2.682705e+09
1332    2.780642e+09
1333    3.101107e+09
1335    3.640807e+09
Name: Anual_Salary, Length: 650, dtype: float64

In [92]:
df[(df['region']=='southwest')&(df['smoker']=='yes')]["age"]

939     19.0
990     38.0
996     20.0
997     19.0
1006    19.0
1008    19.0
1016    32.0
1024    21.0
1030    30.0
1033    36.0
1044    39.0
1045    33.0
1048    31.0
1063    25.0
1067    20.0
1081    39.0
1099    42.0
1106    43.0
1114    49.0
1117    48.0
1128    50.0
1138    47.0
1140    54.0
1192    25.0
1194    23.0
1198    24.0
1201    19.0
1203    19.0
1204    27.0
1208    34.0
1209    22.0
1212    26.0
1216    29.0
1219    19.0
1221    30.0
1225    33.0
1234    43.0
1238    20.0
1239    36.0
1242    31.0
1245    44.0
1248    30.0
1254    49.0
1256    37.0
1260    39.0
1261    37.0
1271    46.0
1283    50.0
1298    29.0
1304    37.0
1315    64.0
1316    63.0
1317    61.0
1321    64.0
1322    60.0
1327    63.0
1331    28.0
1332    60.0
Name: age, dtype: float64

In [93]:
df[df['smoker']=='yes']

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
892,18.0,male,17.290,2.0,yes,28359.89423,NaN,948296.0,2.289506e+06,1.0,2.041853e+08,northeast,12829.45510
935,18.0,male,21.565,0.0,yes,15396.10359,13.0,947473.0,1.136348e+07,1.0,2.103745e+08,northeast,13747.87235
939,19.0,female,21.700,0.0,yes,51149.48177,13.0,954114.0,5.207775e+06,1.0,2.314991e+08,southwest,13844.50600
958,18.0,female,21.660,0.0,yes,44379.85038,8.0,961522.0,8.314765e+06,1.0,2.414897e+08,northeast,14283.45940
971,26.0,female,17.195,2.0,yes,39926.67793,21.0,961242.0,9.256594e+06,1.0,2.892198e+08,northeast,14455.64405
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,33.0,female,35.530,0.0,yes,63142.25346,32.0,1091267.0,1.703805e+08,2.0,3.101107e+09,northwest,55135.40209
1334,31.0,female,38.095,1.0,yes,43419.95227,31.0,1107872.0,2.015152e+08,2.0,3.484216e+09,northeast,58571.07448
1335,52.0,male,34.485,3.0,yes,52458.92353,25.0,1092005.0,2.236450e+08,2.0,3.640807e+09,northwest,60021.39897
1336,45.0,male,30.360,0.0,yes,69927.51664,34.0,1106821.0,2.528924e+08,3.0,4.006359e+09,southeast,62592.87309
1337,54.0,female,47.410,0.0,yes,63982.80926,31.0,1100328.0,2.616317e+08,3.0,4.117197e+09,southeast,63770.42801

Merging

In [99]:
import pandas as pd
students=pd.DataFrame({
    "Name":["Meena","Nyra","Olivia","Gastro"],
    "Hometown":["Ongole","USA","UK","Australia"],
    "Age":[23,22,21,20],
    "Gender":["F","M","F","F"]
    })
books=pd.DataFrame({
    "Name":["Ramayana","Mahabharatam","Horror","Science"],
    "Hometown":["Ongole","USA","UK","Meerut"],
    "Age":[23,22,21,20],
    "Rating":["Good","Excellent","Fair","Very Good"]
})
students

     Name   Hometown  Age Gender
0   Meena     Ongole   23      F
1    Nyra        USA   22      M
2  Olivia         UK   21      F
3  Gastro  Australia   20      F

In [100]:
books

           Name Hometown  Age     Rating
0      Ramayana   Ongole   23       Good
1  Mahabharatam      USA   22  Excellent
2        Horror       UK   21       Fair
3       Science   Meerut   20  Very Good

In [102]:
pd.merge(students,books, on="Age")

   Name_x Hometown_x  Age Gender        Name_y Hometown_y     Rating
0   Meena     Ongole   23      F      Ramayana     Ongole       Good
1    Nyra        USA   22      M  Mahabharatam        USA  Excellent
2  Olivia         UK   21      F        Horror         UK       Fair
3  Gastro  Australia   20      F       Science     Meerut  Very Good

In [103]:
pd.merge(students,books,on="Age",how="inner")

   Name_x Hometown_x  Age Gender        Name_y Hometown_y     Rating
0   Meena     Ongole   23      F      Ramayana     Ongole       Good
1    Nyra        USA   22      M  Mahabharatam        USA  Excellent
2  Olivia         UK   21      F        Horror         UK       Fair
3  Gastro  Australia   20      F       Science     Meerut  Very Good

In [104]:
pd.merge(students,books,on="Age",how="left")

   Name_x Hometown_x  Age Gender        Name_y Hometown_y     Rating
0   Meena     Ongole   23      F      Ramayana     Ongole       Good
1    Nyra        USA   22      M  Mahabharatam        USA  Excellent
2  Olivia         UK   21      F        Horror         UK       Fair
3  Gastro  Australia   20      F       Science     Meerut  Very Good

In [105]:
pd.merge(students,books,on="Age",how="right")

   Name_x Hometown_x  Age Gender        Name_y Hometown_y     Rating
0   Meena     Ongole   23      F      Ramayana     Ongole       Good
1    Nyra        USA   22      M  Mahabharatam        USA  Excellent
2  Olivia         UK   21      F        Horror         UK       Fair
3  Gastro  Australia   20      F       Science     Meerut  Very Good

In [106]:
pd.merge(students,books,on="Age",how="outer")

   Name_x Hometown_x  Age Gender        Name_y Hometown_y     Rating
0  Gastro  Australia   20      F       Science     Meerut  Very Good
1  Olivia         UK   21      F        Horror         UK       Fair
2    Nyra        USA   22      M  Mahabharatam        USA  Excellent
3   Meena     Ongole   23      F      Ramayana     Ongole       Good

In [107]:
customers = pd.DataFrame({
    "Cust_Id":[101,102,103,104],
    "Name":["Ram", "Sam", "khushi", "Riya"]
})

orders = pd.DataFrame({
    "Cust_Id":[101,102,105],
    "Order":["Pizza", "Noodles", "Burger"]
})

In [108]:
#inner merge
pd.merge(customers,orders,on="Cust_Id",how="inner")

   Cust_Id Name    Order
0      101  Ram    Pizza
1      102  Sam  Noodles

In [109]:
pd.merge(customers,orders,on="Cust_Id",how="left")

   Cust_Id    Name    Order
0      101     Ram    Pizza
1      102     Sam  Noodles
2      103  khushi      NaN
3      104    Riya      NaN

In [110]:
pd.merge(customers,orders,on="Cust_Id",how="right")

   Cust_Id Name    Order
0      101  Ram    Pizza
1      102  Sam  Noodles
2      105  NaN   Burger

In [111]:
pd.merge(customers,orders,on="Cust_Id",how="outer")

   Cust_Id    Name    Order
0      101     Ram    Pizza
1      102     Sam  Noodles
2      103  khushi      NaN
3      104    Riya      NaN
4      105     NaN   Burger

Encoding

In [112]:
#o & 1's can be easily understand by machines but the words cannot be understood if we try to convert them they will raise an error
import pandas as pd
df = pd.DataFrame({'cust_id':[101,102,103,104,105],
                   'age':[21,24,25,21,24],
                   "gender":["male",'female','male','female','female'],
                   "ratings":['excellent','good','average','average','good']})

the process of conversion of text into numbers into text is called encoding
Numerical Data -- which is quantitative data, which consists of numbers and numeric values
Categorical Data -- categories or groups will exists

In [ ]:
# 1. Nominal Data
# no order exists
# color - red, blue, green, yellow, pink, orange
#         blue, red, green, pink, yellow
# cities - delhi, pune, blr, mumbai
# names, fruits, cars, flowers, bikes, ac, brands, animals, phones, veggies

In [ ]:
# # 2. Ordinal Data
# There is some order
# Customer satisfaction
# Excellent, good, average, poor, very poor
# education degrees
# school, graduation, pg, phd
# age, ranks, feedback, classes, perfomance of employee or students, salary, income slabs

nominal data-one-hot encoding,label encoding

In [115]:
#label encoding
color=pd.DataFrame({
    "SNO":[1,2,3,4,5],
    "colors":["green","skyblue","green","red","red"]
})
color

   SNO   colors
0    1    green
1    2  skyblue
2    3    green
3    4      red
4    5      red

In [118]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
import pandas as pd
df5=pd.DataFrame({
    "Gender":["Male","Female","Male","Female"]
})

In [119]:
df5["Gender"]=le.fit_transform(df5["Gender"])

In [120]:
df5

   Gender
0       1
1       0
2       1
3       0

One-hot Encoding

In [121]:
df6 = pd.DataFrame({'cust_id':[101,102,103,104,105],
                   'age':[21,24,25,21,24],
                   "gender":["male",'female','male','female','female'],
                   "ratings":['excellent','good','average','average','good']})

In [122]:
pd.get_dummies(df6,columns=["gender"])

   cust_id  age    ratings  gender_female  gender_male
0      101   21  excellent          False         True
1      102   24       good           True        False
2      103   25    average          False         True
3      104   21    average           True        False
4      105   24       good           True        False

In [123]:
import pandas as pd
df7= pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Blue"]
})
encoded = pd.get_dummies(df7, columns=["Color"])
print(encoded)

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3        True        False      False

In [131]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df8=pd.DataFrame({
    "Color":["Green","red","Blue","red"]
})
encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df8[["Color"]])
print(encoded)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]

In [132]:
color = pd.DataFrame({'S.no.':[1,2,3,4,5, 6, 7, 8, 9, 10],
                       'colors':['red','green','red','red','green', "blue","pink","blue","pink", 'red']})

In [134]:
pd.get_dummies(color,columns=["colors"])
print(color)

   S.no. colors
0      1    red
1      2  green
2      3    red
3      4    red
4      5  green
5      6   blue
6      7   pink
7      8   blue
8      9   pink
9     10    red